-- MySQL Script generated by MySQL Workbench
-- Mon Oct 21 13:44:11 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------



-- -----------------------------------------------------
-- Table `mydb`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `employee` (
  `id` INT NOT NULL,
  `emp_fname` VARCHAR(45) NULL,
  `emp_mname` VARCHAR(45) NULL,
  `emp_lname` VARCHAR(45) NULL,
  `emp_pnumber` VARCHAR(45) NULL,
  `emp_email` VARCHAR(45) NULL,
  `emp_position` VARCHAR(45) NULL,
  `emp_hire_date` VARCHAR(45) NULL,
  `emp_salary` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`applicant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `applicant` (
  `id` INT NOT NULL,
  `applicant_fname` VARCHAR(45) NULL,
  `applicant_mname` VARCHAR(45) NULL,
  `applicant_lname` VARCHAR(45) NULL,
  `applicant_edubg` VARCHAR(45) NULL,
  `applicant_despos` VARCHAR(45) NULL,
  `employee_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_applicant_employee_idx` (`employee_id` ASC),
  CONSTRAINT `fk_applicant_employee`
    FOREIGN KEY (`employee_id`)
    REFERENCES `employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
